# Generated by Django 5.1.1 on 2024-09-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static\\image\\sedih-banget.png', upload_to='products/'),
            preserve_default=False,
        ),
    ]
